---
- hosts: webserver
  become: yes
  tasks:
    - name: installing webserver on Ubuntu
      apt:
       namee: apache2
       state: present
       ignore_errors: yes
      notify: restartwebserver

  handlers:
    - name: restartwebserver
      service: 
       name: apache2
       state: started
