---
- hosts: 
  become: yes
  tasks:
    - name: install webserver on ubuntu
      apt:
        name: apache2
        state: present
    - name: start webserver on ubuntu
      apt:
        name: apache2
        state: started
  
