---
- hosts: webserver
  become: yes
  tasks:
     - name: install webserver on RedHat
       yum:
        name: httpd
        state: present
     - name: starting webserver on RedHat
       service:
        name: httpd
        state: started