---
- hosts: webserver
  become: yes
  tasks:
    - name: install java on Ubuntu
      apt:
        name: "{{installjavaonUbuntu}}"
        state: present
      when: ansible_os_family== "Debian"

    - name: install java on Redhat
      yum:
        name: "{{installjavaonRedHat}}"
        state: present
      when: ansible_os_family== "RedHat"
