---
- hosts: webserver
  become: yes
  tasks:
  - name: installing git,tree,wget on ubuntu
    apt:
      name: "{{item}}"
      state: present
    loop: 
      - git
      - tree 
      - wget 
    when: ansible_os_family == "Debian"

  - name: installing git,tree,wget on redhat
    yum:
      name: "{{item}}"
      state: present
    loop: 
      - git
      - tree 
      - wget 
    when: ansible_os_family == "RedHat"

